"""create evidence and cases

Revision ID: 825dd75fbc71
Revises: 9732b7dc9ea5
Create Date: 2026-09-08 01:04:27.744066

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '825dd75fbc71'
down_revision: str | None = '9732b7dc9ea5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_created_at'), ['created_at'], unique=False)

    op.create_table('evidence_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_case', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_case_evidence_id'), ['evidence_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_case', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_case_evidence_id'))

    op.drop_table('evidence_case')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_created_at'))

    op.drop_table('evidence')
    # ### end Alembic commands ###
