"""add_todo_due_date

Revision ID: 84f85024f9a1
Revises: 852feffadbc6
Create Date: 2026-09-08 23:37:53.715795

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '84f85024f9a1'
down_revision: str | None = '852feffadbc6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
