"""add_todo_order

Revision ID: 852feffadbc6
Revises: c5fa1f53d705
Create Date: 2026-09-08 23:34:14.395525

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '852feffadbc6'
down_revision: str | None = 'c5fa1f53d705'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
