"""create memos

Revision ID: 9732b7dc9ea5
Revises: 
Create Date: 2026-09-07 01:39:39.506951

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '9732b7dc9ea5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memos_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memos_created_at'))

    op.drop_table('memos')
    # ### end Alembic commands ###
