"""create_bookmark_groups

Revision ID: 9838577e7b10
Revises: 9a9dd67e44fc
Create Date: 2026-09-08 19:11:39.807340

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '9838577e7b10'
down_revision: str | None = '9a9dd67e44fc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookmark_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmark_groups_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_bookmarks_group_id'), ['group_id'], unique=False)
        batch_op.create_foreign_key('fk_bookmarks_group_id_bookmark_groups', 'bookmark_groups', ['group_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bookmarks_group_id_bookmark_groups', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_bookmarks_group_id'))
        batch_op.drop_column('order')
        batch_op.drop_column('group_id')

    with op.batch_alter_table('bookmark_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmark_groups_created_at'))

    op.drop_table('bookmark_groups')
    # ### end Alembic commands ###
