"""create evidence blocks

Revision ID: a6aca93cb37f
Revises: 825dd75fbc71
Create Date: 2026-09-08 01:52:34.121870

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'a6aca93cb37f'
down_revision: str | None = '825dd75fbc71'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('text', 'image', 'table', name='blockkind', native_enum=False), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evidence_case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_block', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_block_case_id'), ['case_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_block', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_block_case_id'))

    op.drop_table('evidence_block')
    # ### end Alembic commands ###
