"""create_todos

Revision ID: c5fa1f53d705
Revises: 9838577e7b10
Create Date: 2026-09-08 23:17:03.087980

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'c5fa1f53d705'
down_revision: str | None = '9838577e7b10'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todos_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_todos_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todos_created_at'))
        batch_op.drop_index(batch_op.f('ix_todos_completed_at'))

    op.drop_table('todos')
    # ### end Alembic commands ###
