"""add_todo_source_memo_id

Revision ID: e6d3dfcc041d
Revises: 84f85024f9a1
Create Date: 2026-09-08 23:43:43.783526

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e6d3dfcc041d'
down_revision: str | None = '84f85024f9a1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_memo_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_todos_source_memo_id'), ['source_memo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todos_source_memo_id'))
        batch_op.drop_column('source_memo_id')

    # ### end Alembic commands ###
